# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 65264d8bf7ed8d692de362787d0e8e0951902fc38935fd4a7b89c45badf8ad4637e64907c52ab61b80bd0a09c4f28862c6a34754a625458d12cd5a9dc9bd815e

test:
  secret_key_base: db0f2aa5f8bed631efb99214c6c3ff030f84a0844ea5b5cc9b2e1463c4eeec6a4e180f083b2a66625258f0933379398297af18509e3081d21cd1fc83f0d4ac9f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
